#!/bin/bash
cd /tmp/rec
rm -rf .repo
source build/envsetup.sh
lunch omni_RMX2151-eng #edit this
export SKIP_API_CHECKS=true ##use additional flags if you need(optional)
export SKIP_ABI_CHECKS=true ##use additional flags if you need(optional)
export ALLOW_MISSING_DEPENDENCIES=true ##use additional flags if you need(optional)
#necessary flags
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 40G
#ccache -o compression=true
ccache -z
ccache -c

mka recoveryimage
mkdir temporary
cp -R out/target/product/RMX2151 temporary/RMX2151
cd temporary/RMX2151
mv recovery.img RMX2151_PBRP_recovery.img
cd -
echo "
"
curl --upload-file ./temporary/RMX2151/RMX2151_PBRP_recovery.img https://transfer.sh/  #edit this
echo "
"
curl --upload-file ./temporary/RMX2151/*zip https://transfer.sh/  #edit this
echo "
"
#####
