#!/bin/bash
cd /tmp/rec
rm -rf .repo
sed -i "s/add_lunch_combo/COMMON_LUNCH_CHOICES/" device/realme/RMX2151/AndroidProducts.mk
sed -i "s/add_lunch_combo/COMMON_LUNCH_CHOICES/" device/realme/RMX2151/vendorsetup.sh
rm device/realme/RMX2151/recovery/root/init*
source build/envsetup.sh
lunch omni_RMX2151-eng #edit this
export SKIP_API_CHECKS=true ##use additional flags if you need(optional)
export SKIP_ABI_CHECKS=true ##use additional flags if you need(optional)
export ALLOW_MISSING_DEPENDENCIES=true ##use additional flags if you need(optional)
#necessary flags
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 40G
#ccache -o compression=true
ccache -z
ccache -c

mka recoveryimage -j40

source build/envsetup.sh
mka recoveryimage
ls out/target/product/RMX2151/

mkdir temporary
cp -R out/target/product/RMX2151 temporary/RMX2151
cd temporary/RMX2151
mv recovery.img RMX2151_PBRP_recovery.img
cd -
curl -sL https://git.io/file-transfer | sh
./transfer wet ./out/error*

curl -sL https://git.io/file-transfer | sh
./transfer wet ./out/target/product/RMX2151/*.zip

curl -sL https://git.io/file-transfer | sh
./transfer wet ./out/target/product/RMX2151/*.img

echo "
"
curl --upload-file ./out/error* https://transfer.sh/  #edit this
echo "
"

curl --upload-file ./temporary/RMX2151/RMX2151_PBRP_recovery.img https://transfer.sh/  #edit this
echo "
"
curl --upload-file ./temporary/RMX2151/*zip https://transfer.sh/  #edit this
echo "
"
#######################################################
