#!/bin/bash
sudo apt install wget
sudo apt-get install tmate
tmate
q
tmate show-message
sudo apt update
sudo apt install git
git clone https://github.com/akhilnarang/scripts
cd scripts
bash setup/android_build_env.sh


mkdir -p /tmp/rec
cd /tmp/rec

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice.Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
git config --global user.name "noobyysauraj"
git config --global user.email "gitsauraj@gmail.com"

# Initialize the latest stable branch
repo init -u git://github.com/PitchBlackRecoveryProject/manifest_pb -b android-11.0

# Sync the latest stable branch
repo sync -j40


pwd
ls

#delete these lines, and replace with your own lines of device sauce
git clone https://github.com/noobyysauraj/pbrp_realme_RMX2151.git device/realme/RMX2151
#
cd /tmp/rec
#########################################################################################################################################
